### ISSUE TITLE
Version in hackage doesn't work with GHC 7.10

### ISSUE THREAD

**Issue by chathhorn** [hguenther/smtlib2#1]
I don't suppose I could convince you to put up a version in Hackage compatible with GHC 7.10?

Thanks!

**Comment by hguenther** [comment]
Am 2015-10-21 um 07:52 schrieb Chris Hathhorn:
> I don't suppose I could convince you to put up a version in Hackage
> compatible with GHC 7.10?

Actually, since I'm on 7.10 at the moment myself, that should not pose
much of a problem. I uploaded a candidate at
http://hackage.haskell.org/package/smtlib2-0.3/candidate, can you let me
know if it works for you?

**Comment by chathhorn** [comment]
That works. Thanks!

**Comment by hguenther** [comment]
Fixed by de1393075a48a92c0fbe063b7eb98654697412c8
