### ISSUE TITLE
please push current version to hackage

### ISSUE THREAD

**Issue by jwaldmann** [hguenther/smtlib2#4]
hackage has 0.3.1, this repo has 1.0 ?

one difference I see is that 1.0 has the `.+.` operator, which is convenient.

0.3 has `plus` but the  code example on https://hackage.haskell.org/package/smtlib2-0.3.1/docs/Language-SMTLib2.html is wrong (`plus [x,y]` should be `app plus [x,y]`)

**Comment by hguenther** [comment]
Version 1.0 is now available on hackage: http://hackage.haskell.org/package/smtlib2-1.0
