### ISSUE TITLE
how to print the formula?

### ISSUE THREAD

**Issue by jwaldmann** [hguenther/smtlib2#5]
Is there an easy way to print the constraint that gets sent to the solver?

For reference, ersatz has https://hackage.haskell.org/package/ersatz-0.3.1/docs/Ersatz-Problem.html#v:runSAT-39- , which I can use like this:
```
Prelude> import Ersatz
Prelude Ersatz> runSAT' (do x <- exists ; assert x ; return x)
(Var 2,SAT 2 ((1) & (2)) mempty)
```
(this is very useful for teaching)

One option would be to write a "solver" that just prints its input to stderr, and returns "unknown".

**Comment by hguenther** [comment]
You can use the smtlib2-debug package (in the "backends" directory) to view the complete SMTLib communication stream with the solver.

**Comment by hguenther** [comment]
The package is now also available on hackage: http://hackage.haskell.org/package/smtlib2-debug
