### ISSUE TITLE
GPL 3

### ISSUE THREAD

**Issue by mikeplus64** [hguenther/smtlib2#9]
I have a proprietary project where I'd like to use this, but sadly switching our own licenses/using GPL is not an option right now. If smtlib2 were licensed under a more permissive license (e.g. LGPL), I'd be able to use it here.

(I do have to acknowledge the fundamental selfishness of this request -- feel free to close this with extreme prejudice. This is just a *really* nice and modern library, especially in comparison to the relatively awkward and lumbering sbv.)

**Comment by hguenther** [comment]
Thank you for your interest in my library! Unfortunately, I don't want to put the library under a license that would allow it to become part of non-free software.

**Comment by mikeplus64** [comment]
Fair enough
